name: Java CI with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: |
        docker build -t my-spring-boot-app .
        docker images  # Optional: List Docker images for verification

    - name: Start PostgreSQL container
      run: docker-compose up -d db

    - name: Wait for PostgreSQL to start
      run: docker-compose exec db pg_isready -q -h localhost -U user -d mydb

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name my-app --network container:db my-spring-boot-app

    - name: Check running containers
      run: docker ps -a

    - name: Test API endpoint
      run: |
        curl -s -S http://localhost:8080/data/1
        # Optionally validate the response here

    - name: Stop PostgreSQL container
      run: docker-compose down
