name: Java CI with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: |
        docker build -t my-spring-boot-app .
        docker images  # Optional: List Docker images for verification

    - name: Start PostgreSQL container
      run: docker-compose up -d db

    - name: Wait for PostgreSQL to start
      run: |
        echo "Waiting for PostgreSQL to start..."
        until docker-compose exec db pg_isready -q -h localhost -U user -d mydb; do
          >&2 echo "Postgres is unavailable - sleeping"
          sleep 1
        done
        echo "PostgreSQL is up - continuing"

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name my-app --network restspringdockercicd_default my-spring-boot-app

    - name: Wait for the app to start
      run: |
        echo "Waiting for the app to start..."
        ATTEMPTS_LEFT=30
        until [ $ATTEMPTS_LEFT -eq 0 ] || curl -s http://localhost:8080/data/1; do
          echo "Waiting for the app to be accessible..."
          sleep 2
          ATTEMPTS_LEFT=$((ATTEMPTS_LEFT - 1))
        done
        if [ $ATTEMPTS_LEFT -eq 0 ]; then
          echo "The app did not start in time."
          docker logs my-app  # Add logs for debugging
          exit 1
        fi
        echo "The app is up - continuing"

    - name: Check running containers
      run: docker ps -a

    - name: Test API endpoint
      run: |
        RESPONSE=$(curl -s -S http://localhost:8080/data/1)
        echo "Response from API: $RESPONSE"
        # Optionally v
